version: "3.8"

services:
  app:
    image: node:20
    container_name: react_container
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "8082:3000"
    command: sh -c "npm ci && npm run dev"
