version: '3.8'

services:
  admin:
    image: node:20
    container_name: immo-client
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:3000"
    command: sh -c "npm ci && npm run dev"